<?xml version="1.0" encoding="utf-8"?><Database Name="myDB" Class="GAMEDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\myDB.mdf;Integrated Security=True" SettingsObjectName="FinalProjectClient.Properties.Settings" SettingsPropertyName="myDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TblPos" Member="TblPos">
    <Type Name="TblPo">
      <Column Name="GameId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" IsPrimaryKey="true"/>
      <Column Name="stepOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" IsPrimaryKey="true"/>
      <Column Name="srcPosX" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="srcPosY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="destPosX" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="destPosY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TblGame_TblPo" Member="TblGame" ThisKey="GameId" OtherKey="GameId" Type="TblGame" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblGame" Member="TblGames">
    <Type Name="TblGame">
      <Column Name="GameId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="TblGame_TblPo" Member="TblPos" ThisKey="GameId" OtherKey="GameId" Type="TblPo" />
    </Type>
  </Table>
</Database>